---
name: Maven CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21

    steps:
      - uses: actions/checkout@v4

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml
...